import type { Metadata } from "next"
import type { IChildren } from "../lib/models/app/general/interfaces/IChildren"
import type { JSX } from "react/jsx-runtime"
import { MINECRAFT_FIVE, MINECRAFT_TEN, MOJANGLES } from "./LocalFonts"
import "@/oliverperzyk/styles/GlobalStyles.css"

/**
 * @summary Metadata of the application.
 * @description Configuration of the application.
 */
const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

/**
 * @summary Root layout of the application.
 * @description Configuration of the root layout of the application.
 * @param children - The children of the component.
 * @returns The root layout of the application.
 */
function RootLayout({ children }: Readonly<IChildren>): JSX.Element {
    return (
        <html
            lang="en-US"
            className={`${MINECRAFT_FIVE.variable} ${MINECRAFT_TEN.variable} ${MOJANGLES.variable} h-full antialiased`}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    )
}

export { metadata }
export default RootLayout
